// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEL-r0xN4-s89n_j6k2O39x397wr4stBI',
    appId: '1:389856255746:web:4e19401c485c18cde9ac1b',
    messagingSenderId: '389856255746',
    projectId: 'taskmanagerapp-86091',
    authDomain: 'taskmanagerapp-86091.firebaseapp.com',
    storageBucket: 'taskmanagerapp-86091.appspot.com',
    measurementId: 'G-8RMFD9QD8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBavVRRDMc7bVSs8AgpRY86Ao1_3Ig9Zi4',
    appId: '1:389856255746:android:448c82daca8090bce9ac1b',
    messagingSenderId: '389856255746',
    projectId: 'taskmanagerapp-86091',
    storageBucket: 'taskmanagerapp-86091.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJfLrGXf_Rj43qjrdvLEj1mr33NZe6n9c',
    appId: '1:389856255746:ios:099c0327441243c1e9ac1b',
    messagingSenderId: '389856255746',
    projectId: 'taskmanagerapp-86091',
    storageBucket: 'taskmanagerapp-86091.appspot.com',
    iosBundleId: 'com.example.taskManagerApp',
  );
}
